spring:
  application:
    name: project-cloud

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health, info

  cloud:
    aws:
      region:
        static: ap-northeast-2

  servlet:
    multipart:
      max-request-size: 10MB