name: CI Pipeline

# main 브랜치 push 또는 PR
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# OIDC 토큰 요청 권한
permissions:
  id-token: write   # OIDC 토큰 요청용
  contents: read    # 코드 체크아웃용 (체크아웃 - Repo에 있는 코드를 Runner에 옮김)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: 코드 가져오기
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: 스프링 빌드를 위한 Java 17 설치
      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'

      # gradlew 파일에 실행 권한 추가
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Step 3: Gradle 캐시
      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Step 5: JAR 빌드
      - name: Build JAR
        run: ./gradlew bootJar



